version: '3'

services:
  web:
    image: django-image:latest
    command: gunicorn core.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:
    driver: bridge
