# Generated by Django 4.2.9 on 2024-02-05 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='poll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
            preserve_default=False,
        ),
    ]
